<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Applications_of_Linear_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from scipy.linalg import solve
import numpy as np

# Systems of Linear Equations


## Systems of Linear Equations can be solved with arrays and NumPy

In [5]:
## Createing matices
A = np.array([[4,5],[3,-2]])
print(A)
B = np.array([[7],[11]])
print(B)

[[ 4  5]
 [ 3 -2]]
[[ 7]
 [11]]


In [13]:
## Solve
X=np.linalg.inv(A).dot(B)
print(X)

[[ 3.]
 [-1.]]


In [12]:
## using numpy inv
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 0.08695652  0.2173913 ]
 [ 0.13043478 -0.17391304]]


In [14]:
## Getting dot product to solve
X = np.dot(inv_A,B)
print(X)

[[ 3.]
 [-1.]]


In [15]:
## Using numpy solve
X = np.linalg.solve(A,B)
print(X)

[[ 3.]
 [-1.]]


In [16]:
## Using Scipy solve
X = solve(A,B)
print(X)

[[ 3.]
 [-1.]]
