<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

from numpy.linalg import eig

In [50]:
## Define Matrices
A = np.array([[-12, 3], [4, 1]])
inv_A = np.linalg.inv(A)

B = np.array([0, 0])

## Solve
X = np.linalg.solve(A, B)
print(X)

X = np.dot(inv_A, B)
print(X)

[-0.  0.]
[0. 0.]


In [51]:
## Define Matrix A
A = np.array([[-6, 3], [4, 5]])
print("Vector A:\n", A)

## Solve for eigenvalues and eigenvectors
w, v = eig(A)
# v = v.round()
print("Eigenvalues:\n", w)
print("Eigenvectors:\n", v)

Vector A:
 [[-6  3]
 [ 4  5]]
Eigenvalues:
 [-7.  6.]
Eigenvectors:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


#Example 2

In [64]:
## Define Matrix A
A = np.array([[2, 2, 4], [1, 3, 5], [2, 3, 4]])

## Solve for eigenvalues and eigenvectors
w, v = eig(A)
print("Eigenvalues:\n", w)
print("Eigenvectors:\n", v)
w = w.round()
v = v.round()
print("Eigenvalues:\n", w)
print("Eigenvectors (1):\n", v)

c = np.dot(A ,v)
print(c)


Eigenvalues:
 [ 8.80916362  0.92620912 -0.73537273]
Eigenvectors:
 [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
Eigenvalues:
 [ 9.  1. -1.]
Eigenvectors (1):
 [[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
