<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Finals Exam

In [39]:
import numpy as np



---


## Problem 1
Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have?

Given:
\begin{equation}
A + B + C = 89
\end{equation}
\begin{equation}
A = C - 9
\end{equation}
\begin{equation}
B = 3C
\end{equation}
\
\
Rearrangging...
\begin{equation}
A + B + C = 89
\end{equation}
\begin{equation}
A - C = 9
\end{equation}
\begin{equation}
B - 3C = 0
\end{equation}
\
\
Matrix Form:
\begin{equation}
A = 
\begin{bmatrix}
1 & 1 & 1 \\
1 & 0 & -1 \\
0 & 1 & -3
\end{bmatrix}
=
\begin{bmatrix}
89\\ 9 \\ 0 
\end{bmatrix}
\end{equation}

In [75]:
## Declaringg the matrix
A = np.array([[1,1,1], [1,0,-1], [0,1,-3]])
B = np.array([89, -6, 0])

## Solving for the values of A, B, & C
x = np.linalg.solve(A,B).astype(int)

## Output
print("\nResult:")
print("Student A has Php", x[0])
print("Student B has Php", x[1])
print("Student C has Php", x[2])


Result:
Student A has Php 13
Student B has Php 57
Student C has Php 19




---


## Problem 2


Solve each system

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 




In [76]:
## Declaring the matrices
A = np.array([[3, -1, 1], [9, -3, 3], [-12, 4, -4]])
B = np.array([5, 15, -20])

A_det = np.linalg.det(A)
print("Determinant: ", A_det)

Determinant:  0.0


**Answer:** The determinant of matrix A is 0, meaning that
the system has linearly dependent equations.




---


## Problem 3
Problem 3. Consider the matrix,

\begin{equation}
A = 
\begin{bmatrix}
    8 & 5 & -6 \\
    -12 & -9 & 12 \\
    -3 & -3 & 5
    \end{bmatrix}
\end{equation}


1.   Find the eigenvalue/s
2.   Find the eigenvectors

In [77]:
## Decalaring the matrix
A = np.array([[8,5,-6], [-12,-9,12], [-3,-3,5]])
## Getting the eigenvalue(s) and eigenvetors
w,v = np.linalg.eig(A)

## Printing matrix A
print("Matrix A:\n", A, "\n")

## Printing the eigenvalue(s) and eigenvetors
print("Eigenvalue/s:\n", w.astype(int) , "\n")   # np.astype was used to convert float to int
print("Eigenvectors:\n", v.astype(int) , "\n")


Matrix A:
 [[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

Eigenvalue/s:
 [0 2 2] 

Eigenvectors:
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 

