<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Finding the **Inverse** of a Matrix using Pyhton


In [71]:
# Creating a 2x2 matrix
A = np.array([[1,2],[4,7]])
print(A)

[[1 2]
 [4 7]]


In [72]:
# Getting the inverse of matrix A
B = np.linalg.inv(A)
print(B)

[[-7.  2.]
 [ 4. -1.]]


In [73]:
# Checking/Veryfying
C = np.dot(A, B)
print(C)

[[1. 0.]
 [0. 1.]]


# Python Program to **Transpose** a 3x3 Matrix A=([6,1,1],[4,-2,5],[2,8,7])

In [74]:
# Transpose of a 3x3 matrix
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
B = np.transpose(A)
print("Matrix: \n", A)
print("Transpose: \n", B)

Matrix: 
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
Transpose: 
 [[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [79]:
# Inverse of a 3x3 matrix
C = np.array([[6,-1,1],[4,2,5],[2,8,-7]])
D = np.linalg.inv(C)
print("Matrix: \n",C)
print("Inverse: \n",D)

# Checking if D is the inverse of C
m = np.dot(C, D) # This should creates an identity matrix
n = np.array(m, dtype=int) # This cleans up the messy floating points
print("Check: \n",n)

Matrix: 
 [[ 6 -1  1]
 [ 4  2  5]
 [ 2  8 -7]]
Inverse: 
 [[ 0.16167665 -0.00299401  0.02095808]
 [-0.11377246  0.13173653  0.07784431]
 [-0.08383234  0.1497006  -0.04790419]]
Check: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


# **Transposing** and **Inversing** a 4x4 Matrix

In [76]:
# Creating a 4x matrix, making sure to assign negative(-) values
A = np.array([[1,-2,3,4],[3,4,-5,6],[6,7,8,-9],[9,-8,7,6]])
print(A)

[[ 1 -2  3  4]
 [ 3  4 -5  6]
 [ 6  7  8 -9]
 [ 9 -8  7  6]]


## INVERSE
#### Getting the Inverse of the Matrix

In [77]:
# Getting the inverse of the 4x4 matrix
A_inv = np.linalg.inv(a1)

# Displaying the output
print("Matrix: \n",A)
print("Inverse: \n",A_inv)

# Checking if the inverse is correct
x = np.dot(A, A_inv) # This should creates an identity matrix
y = np.array(x, dtype=int) # This cleans up the messy floating decimals
print("Check: \n",y)

Matrix: 
 [[ 1 -2  3  4]
 [ 3  4 -5  6]
 [ 6  7  8 -9]
 [ 9 -8  7  6]]
Inverse: 
 [[-0.18409091  0.06060606  0.02272727  0.09621212]
 [ 0.13977273  0.06818182  0.05681818 -0.07613636]
 [ 0.23181818 -0.04545455  0.04545455 -0.04090909]
 [ 0.19204545  0.0530303  -0.01136364 -0.03143939]]
Check: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## TRANSPOSE
#### Getting the Transposed Matrix

In [78]:
# Getting the transposition of the 4x4 Matrix
A_trans = np.transpose(a1)

# Displaying the output
print("Matrix: \n",A)
print("Transposed: \n",A_trans)

Matrix: 
 [[ 1 -2  3  4]
 [ 3  4 -5  6]
 [ 6  7  8 -9]
 [ 9 -8  7  6]]
Transposed: 
 [[ 1  3  6  9]
 [-2  4  7 -8]
 [ 3 -5  8  7]
 [ 4  6 -9  6]]
