<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practical Lab Exam 1**

In [ ]:
import numpy as np

## Problem 1

In [69]:
W = np.array([[1, -3], [2, -2], [3, 1]])
X = np.array([[3, 2, 1], [-1, 2, 3], [2, -1, 1]])
Y = np.array([[1, 2, 0], [0, -1, 2]])
Z = np.array([[0, 1], [2, 3]])

### a.

In [70]:
np.dot(W,Y)

array([[ 1,  5, -6],
       [ 2,  6, -4],
       [ 3,  5,  2]])

### b.

In [ ]:
print(np.add(Z, Z))

[[0 2]
 [4 6]]


### c.

In [74]:
print(np.multiply(3, X))

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


## Problem 2

### a. 
The product of (YW)^2 is not defined

_The statement is **FALSE**_

In [75]:
# using numpy, we square the 
# product of matcies Y and W
np.power(np.dot(Y, W), 2)

array([[25, 49],
       [16, 16]])

### b.
WY - X

_The statement is **TRUE**_


In [72]:
# useing numpy, we subtract the
# matrix X from the product of 
# matrices W  and Y
np.subtract(np.dot(W,Y),X)

array([[-2,  3, -7],
       [ 3,  4, -7],
       [ 1,  6,  1]])

### c.
YW – Z^2 

_The statement is **FALSE**_

In [73]:
# using numpy, we subtract the
# square of matrix Z from the 
# product of matrices y and W
np.subtract(np.dot(Y,W),np.power(Z,2))

array([[ 5, -8],
       [ 0, -5]])