<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Question 1

In [38]:
# Creating a 4 x 4 matrix
# a parameter dtype in defined to clean decimal points in the output
C = np.zeros([4,4], dtype=int) 

# Filling in matrix's diagonals with the value 1
np.fill_diagonal(C, 1) 

# printing the output
print(C)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Question 2

In [39]:
# SOLUTION 01
## Multiplying matrix C by 2 with * operator
## This is the same as C = C * 2
C *= 2                

print("using C *= 2: \n", C)

# SOLUTION 02
## Multiplying matrix C by 2 with the multiply() function
np.multiply(2, C)

print("\nusing np.multiply(2, C):\n", C)

using C *= 2: 
 [[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]

using np.multiply(2, C):
 [[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


# Question 3

In [40]:
# Defining matrices 'A' and 'B'
A = np.array([2,7,4])
B = np.array([3,9,8])

# Assigning the dotproduct of A and B to variable 'output'
output = np.dot(A, B)

# Printing output
print(output)

101
