<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix and Its Operations

In [1]:
import numpy as np

In [2]:
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])

## Sum of Matrices

In [6]:
sum = A+B
print(sum)

[[ 1 -3]
 [ 6  4]]


## Difference of Matrices

In [7]:
## Difference 1
difference1 = A-B
print(difference1)

[[-11   3]
 [  2  -2]]


In [9]:
## Difference2
difference2 = B - B
print(difference2)

[[0 0]
 [0 0]]
