<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vector Spaces and its Operation


In [1]:
import numpy as np

In [2]:
A = np.array([4,3])
B = np.array([2,-5])

In [4]:
print('Vector A is ', A)
print('Vector b is ', B)

Vector A is  [4 3]
Vector b is  [ 2 -5]


## Vector Size, Dimension, and shape

In [16]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

pool = np.array([ball1, ball2])
print("Shape: ",pool.shape)
print("Size: ",pool.size)
print("Dimension: ",pool.ndim)
print("Matrix: \n",pool)

Shape:  (2, 3)
Size:  6
Dimension:  2
Matrix: 
 [[ 1  2  3]
 [ 0  1 -1]]


## Vector Operations


In [18]:
R = A +  B
R

array([ 6, -2])

In [21]:
R = np.add(A,B)
R

array([ 6, -2])

In [23]:
R = np.subtract(A,B)
R

array([2, 8])

## Vector Scaling

In [28]:
A = np.array([1,5,8,9])
S = 5 * A
print("5 *",A)
print(S)

5 * [1 5 8 9]
[ 5 25 40 45]


In [31]:
S = np.multiply(5,A)
S

array([ 5, 25, 40, 45])

## Vector Cross Product

In [41]:
#initialize arrays
A = np.array([2,7])
B = np.array([1,7])

#computefor the cross product
output = np.cross(A,B)

print("A:",A,"\tB:",B)
print(output)

A: [2 7] 	B: [1 7]
7


## Vector Dot Product

In [42]:
output = np.dot(A,B)
output

51