<a href="https://colab.research.google.com/github/AloysiusButacAdu/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Declaring the matrix
A = np.array([[1, 1, 1], [1, 2, 2,], [1, 2, 3]])
B = np.array([[5], [6], [8]])
print(A)
print(B)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[5]
 [6]
 [8]]


In [7]:
# FORMULA: AA^-1X = BA^-1

# Solving for inverse of A
A_inv = np.linalg.inv(A)
print(A_inv)

# Solving for BA^-1
## Same as: np.dot(A_inv, B)
X = A_inv @ B 
print(X)

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[[ 4.]
 [-1.]
 [ 2.]]
