# Matrix and its Operations


In [10]:
import numpy as np

In [9]:
## Creating a 1x3 array (matrix)
a = np.array([1,1,1])
print(a)

[1 1 1]


In [19]:
## Creating a 2x3 matrix
b = np.array([[1,1,1],[2,2,2]]) ## <-- Rectangular array (matrix)
print(b)

[[1 1 1]
 [2 2 2]]


In [18]:
## Creating a 3x3 matrix
c = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(c)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [26]:
## Creating a constant array with all values are constant
d =np.full([3,3],8) ## can use []
d_2 =np.full((3,3),0) ## <-- Square Matrix
print(d)
print(d_2)

[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
## Creating a diagonal matrix
e = np.diagonal(c)
print(c)
print(e)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[1 2 3]


In [32]:
## Creating an identity matrix
f = np.eye(6,dtype=int)
print(f)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [39]:
## Creating a zero matrix
g = np.zeros((4,8),dtype=int)
print(g)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [46]:
## Creating an empty matrix
h = np.empty((0,99))
h_2 = np.empty((5,2)) ## ??????
print(h)
print(h_2)

[]
[[0.00000000e+000 1.82804289e-322]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.16096346e-028]
 [9.82205649e+252 1.11789342e+253]
 [3.00312108e-067 2.65534875e-312]]


In [54]:
## Addition of Matrices
i = np.array([[1,2,3],[4,5,6],[7,8,9]])
j = np.zeros((3,3),dtype=int) ## float + int = float; int + int = int
print(i+j)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
## Subtraction of Matrices
j = np.array([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]])
print(i-j)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
